---
title: "Project"
output: html_document
date: "2025-03-18"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyr)
library(dplyr)
library(ggplot2)
library(shiny)
library(readr)
library(patchwork)
library(tidyverse)
library(DT)
```

```{r}
chess = read_csv("https://uwmadison.box.com/shared/static/8y8ijsi92qugjmjyv1qxiqt2pnmp3h8i.csv")
```

```{r}
# add time_control and rating_group columns
chess = chess %>% 
  separate(increment_code, c("base", "inc"), remove=FALSE) %>% 
  mutate(base = as.integer(base)) %>% 
  mutate(inc = as.integer(inc)) %>% 
  mutate(tgt = base + 40*inc) %>% 
  mutate(time_control = case_when(
    tgt < 3 ~ "Bullet",
    tgt >= 3 & tgt < 8 ~ "Blitz",
    tgt >= 8 & tgt < 25 ~ "Rapid",
    tgt >= 25 ~ "Classical"
  )) %>% 
  select(-c(base, inc)) %>% 
  mutate(rating_group = case_when(
    black_rating > 1500 & white_rating > 1500 ~ "high",
    black_rating <= 1500 & white_rating <= 1500 ~ "low", 
    black_rating > 1500 & white_rating <= 1500 ~ "b>w",
    black_rating <= 1500 & white_rating > 1500 ~ "w>b"
  ))
```

```{r}
# plots white rating against black rating, colored by top openings per group
makePlot = function(x) {
  chess %>%  
    group_by(rating_group) %>%
    mutate(opening = fct_lump_n(opening_name, as.integer(x))) %>%
    filter(opening != "Other") %>%
    ungroup() %>% 
    ggplot() +
    geom_point(aes(white_rating, black_rating, col = opening), alpha = 0.7, size = 3) +
    scale_color_viridis_d() +
    labs(x = "White Rating", y = "Black Rating", title = "Favorite Openings by Rating")
}
```

```{r}
# creates table that lists top x openings for each rating group
makeTable = function(x) {
  chess %>%  
    group_by(rating_group, opening_name) %>%
    summarise(count = n(), .groups = "drop") %>% 
    arrange(rating_group, desc(count)) %>% 
    group_by(rating_group) %>% 
    slice_head(n = as.integer(x)) %>% 
    mutate(rank = row_number()) %>% 
    ungroup() %>% 
    select(-count) %>% 
    pivot_wider(names_from = rating_group, values_from = opening_name) %>% 
    select(rank, low, high, `w>b`, `b>w`)
}
```


```{r}
# shiny app
ui = fluidPage(
  selectInput("top_n", "Top N Openings", choices = c(1:10)),
  br(),
  plotOutput("plot"),
  br(),
  DTOutput("table")
)

server = function(input, output) {
  output$plot = renderPlot(
    makePlot(input$top_n)
  )
  
  output$table = renderDT(
    makeTable(input$top_n), 
    rownames = FALSE
  )
}

shinyApp(ui, server)
```

